# Installs and builds the package (including native modules)
# Using the image: balenalib/raspberrypi3-alpine-node:16
name: Build - Raspberry Pi Zero

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Build the for Raspberry Pi Zero
        run: ./dockcross /bin/bash -c "./build.sh"
      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/coverboy_*.deb
      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/coverboy