# Installs and builds the package (including native modules)
# Using the image: balenalib/raspberrypi3-alpine-node:16
name: Build - Raspberry Pi Zero

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Install ARMv6 binfmt
        run: docker run --privileged --rm tonistiigi/binfmt --install arm
      - name: Create build image for Raspberry Pi Zero
        run: docker build --platform linux/arm/v6 --file Dockerfile --tag raspberry-pi-zero:$(date +%s) .
      - name: Create build directory
        run: mkdir -p build
      - name: Build the for Raspberry Pi Zero
        run: docker run --rm -v ./build:/build raspberry-pi-zero:$(date +%s)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: build/