# Installs and builds the package (including native modules)
# Using the image: balenalib/raspberrypi3-alpine-node:16
name: Build - Raspberry Pi Zero

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Install ARMv6 binfmt
        run: docker run --privileged --rm tonistiigi/binfmt --install arm
      - name: Build for Raspberry Pi Zero
        run: docker build --platform linux/arm/v7 --file Dockerfile --tag raspberry-pi-zero:$(date +%s) .